version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    commit-message:
      prefix: 'chore'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    labels: ['dependencies']

  - package-ecosystem: 'composer'
    directory: '/'
    commit-message:
      prefix: 'chore'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    groups:
      all-dependencies:
        patterns: ['*']
        update-types: ['minor', 'patch', 'major']
    labels: ['dependencies']
    versioning-strategy: 'increase'
